### ISSUE TITLE
Crear un proyecto desde cero con django4 y subirlo a un repositorio en github

### ISSUE THREAD

**Issue by fernandoperezwh** [fernandoperezwh/wh#2]
https://wisphub.atlassian.net/browse/PW-467?focusedCommentId=13822

- [x] Crear un proyecto con django4
  ![image](https://github.com/user-attachments/assets/1852c341-ef59-4200-95b6-b5cb23d6928d)
- [x] Usar la configuración basica del modelo user usando Abstrac User
  ![image](https://github.com/user-attachments/assets/4447307b-5861-472b-a72e-a08d580acd70)
- [x] Deben usar pipenv
  ![image](https://github.com/user-attachments/assets/ffa9019b-16ee-41a5-89fd-6d39f4a41069)
- [x] Debe tener dos archivos de configuracion de entorno uno productivo y otro de desarrollo(No requiere tener contenido)
  ![image](https://github.com/user-attachments/assets/44d1bb61-3e1e-4744-b836-dd22f95ee102)
- [x] Debe tener un settings_server.py configurado(No requiere tener contenido)
  ![image](https://github.com/user-attachments/assets/83c86ec0-f25b-429d-a494-fa0948a9c53f)
- [x] Usar version de django4 y python que soporte dicha version
  ![image](https://github.com/user-attachments/assets/1852c341-ef59-4200-95b6-b5cb23d6928d)
  ![image](https://github.com/user-attachments/assets/64cb5480-ee20-4731-a0ff-af2f19f618cd)
- [x] El nombre del proyecto es a su elección
- [x] Crear repositorio para este proyecto y subirlo
  ![image](https://github.com/user-attachments/assets/fa9de0a5-7429-4321-97db-2c3180311a32)
- [x] Realizar conexion de base de datos con SQLite
  ![image](https://github.com/user-attachments/assets/7af0ef11-0b61-4b9d-8362-d104d7b6734b)
- [x] Configurar su entorno para correr con la consola y el run de pycharm
  ![image](https://github.com/user-attachments/assets/9937af9a-c87a-4eec-aa56-5e249c93fd18)
- [x] Seguir el siguiente esquema de archivo para el proyecto
  ![image](https://github.com/user-attachments/assets/549891b2-036d-4717-a742-298b63356f3f)

**Comment by victor-wh** [comment]
- [x] Revisado y aprobado
